# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'UI Templates/header_students.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_HeaderStudents(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(766, 40)
        self.gridLayout = QtWidgets.QGridLayout(Form)
        self.gridLayout.setObjectName("gridLayout")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setContentsMargins(11, -1, 11, -1)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.lbl_hdr_name = QtWidgets.QLabel(Form)
        self.lbl_hdr_name.setObjectName("lbl_hdr_name")
        self.horizontalLayout_2.addWidget(self.lbl_hdr_name)
        self.lbl_hhr_course = QtWidgets.QLabel(Form)
        self.lbl_hhr_course.setObjectName("lbl_hhr_course")
        self.horizontalLayout_2.addWidget(self.lbl_hhr_course)
        self.lbl_hdr_yrlvl = QtWidgets.QLabel(Form)
        self.lbl_hdr_yrlvl.setObjectName("lbl_hdr_yrlvl")
        self.horizontalLayout_2.addWidget(self.lbl_hdr_yrlvl)
        self.lbl_hdr_gender = QtWidgets.QLabel(Form)
        self.lbl_hdr_gender.setObjectName("lbl_hdr_gender")
        self.horizontalLayout_2.addWidget(self.lbl_hdr_gender)
        self.lbl_hdr_status = QtWidgets.QLabel(Form)
        self.lbl_hdr_status.setObjectName("lbl_hdr_status")
        self.horizontalLayout_2.addWidget(self.lbl_hdr_status)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem)
        self.horizontalLayout_2.setStretch(0, 5)
        self.horizontalLayout_2.setStretch(1, 2)
        self.horizontalLayout_2.setStretch(2, 2)
        self.horizontalLayout_2.setStretch(3, 2)
        self.horizontalLayout_2.setStretch(4, 2)
        self.horizontalLayout_2.setStretch(5, 4)
        self.gridLayout.addLayout(self.horizontalLayout_2, 0, 0, 1, 1)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.lbl_hdr_name.setText(_translate("Form", "Full Name"))
        self.lbl_hhr_course.setText(_translate("Form", "Course"))
        self.lbl_hdr_yrlvl.setText(_translate("Form", "Year Level"))
        self.lbl_hdr_gender.setText(_translate("Form", "Gender"))
        self.lbl_hdr_status.setText(_translate("Form", "Status"))