# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'UI Templates/header_courses.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_HeaderCourses(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(662, 33)
        self.gridLayout = QtWidgets.QGridLayout(Form)
        self.gridLayout.setObjectName("gridLayout")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setContentsMargins(11, -1, 11, -1)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.lbl_courseCode = QtWidgets.QLabel(Form)
        self.lbl_courseCode.setObjectName("lbl_courseCode")
        self.horizontalLayout_2.addWidget(self.lbl_courseCode)
        self.lbl_courseDescription = QtWidgets.QLabel(Form)
        self.lbl_courseDescription.setObjectName("lbl_courseDescription")
        self.horizontalLayout_2.addWidget(self.lbl_courseDescription)
        self.horizontalLayout_2.setStretch(0, 2)
        self.horizontalLayout_2.setStretch(1, 11)
        self.gridLayout.addLayout(self.horizontalLayout_2, 0, 0, 1, 1)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.lbl_courseCode.setText(_translate("Form", "Course Code"))
        self.lbl_courseDescription.setText(_translate("Form", "Course Description"))