# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'UI Templates/widget_courseItemEdit.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_CourseEdit(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        # Remove the fixed size constraint on the form
        # Form.setFixedSize(727, 46)
        
        self.gridLayout = QtWidgets.QGridLayout(Form)
        self.gridLayout.setObjectName("gridLayout")
        # Remove the fixed size constraint on the layout
        # self.gridLayout.setSizeConstraint(QtWidgets.QLayout.SetFixedSize)

        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")

        self.fld_courseCode = QtWidgets.QLineEdit(Form)
        self.fld_courseCode.setObjectName("fld_courseCode")
        self.fld_courseCode.setMaximumHeight(40)  # Set maximum height for the text field
        self.horizontalLayout.addWidget(self.fld_courseCode)

        self.fld_courseName = QtWidgets.QLineEdit(Form)
        self.fld_courseName.setObjectName("fld_courseName")
        self.fld_courseName.setMaximumHeight(40)  # Set maximum height for the text field
        self.horizontalLayout.addWidget(self.fld_courseName)

        self.lbl_status = QtWidgets.QLabel(Form)
        self.lbl_status.setText("")
        self.lbl_status.setObjectName("lbl_status")
        self.horizontalLayout.addWidget(self.lbl_status)

        self.btn_save = QtWidgets.QPushButton(Form)
        self.btn_save.setObjectName("btn_save")
        self.btn_save.setMaximumHeight(40)  # Set maximum height for the button
        self.horizontalLayout.addWidget(self.btn_save)

        self.btn_cancel = QtWidgets.QPushButton(Form)
        self.btn_cancel.setObjectName("btn_cancel")
        self.btn_cancel.setMaximumHeight(40)  # Set maximum height for the button
        self.horizontalLayout.addWidget(self.btn_cancel)

        self.horizontalLayout.setStretch(0, 3)
        self.horizontalLayout.setStretch(1, 13)
        self.horizontalLayout.setStretch(2, 2)
        self.horizontalLayout.setStretch(3, 2)
        
        self.gridLayout.addLayout(self.horizontalLayout, 0, 1, 1, 1)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.fld_courseCode.setText(_translate("Form", "BSCS"))  # Corrected line
        self.btn_save.setText(_translate("Form", "Save"))
        self.btn_cancel.setText(_translate("Form", "Cancel"))
